ARGWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('the-trail/', include('puzzle2.urls')),
    path('countdown/', include('countdown.urls')),
    path('murdergame/', include('murder.urls')),
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

countdown/urls.py
from django.urls import path

from . import views

app_name = 'countdown'
urlpatterns = [
    path('', views.index, name='index'),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
]

murder/urls.py
from django.urls import path

from . import views

app_name = 'murder'
urlpatterns = [
    path('', views.index, name='index'),
]

puzzle2/urls.py
from django.urls import path

from . import views

app_name = 'puzzle2'
urlpatterns = [
    path('4675726e616365/', views.index, name='index'),
    path('incorrect/', views.fail, name='fail'),
    path('test/', views.test, name='test'),
    path('answer/', views.answer, name='answer'),
    path('hmm/', views.success, name='success'),
]

murder/models.py
from django.db import models

# Create your models here.

countdown/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
import datetime


def index(request):
    return render(request, 'countdown/counter.html')

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'homepage/index.html')

murder/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'murder/game.html')

puzzle2/views.py
import random

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


# Create your views here.


def index(request):
    letters = 'WATERMELON'
    for i in range(100):
        letters = letters + random.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    letters = "RKLJQHRTGUGOWFGGRXZVNPDJZESOAOFBFJPBEODQTSYLHXNNHUVPLEGCEONQEZBMWCVUFZNUACBWUEIYPGXPBICFYFSBNRUAKUVYMSAZCHREUUOYKJFXFLIM"
    context = {
        'letters': letters,
    }
    return render(request, 'puzzle2/index.html', context)


def fail(request):
    return render(request, 'puzzle2/fail.html')


def test(request):
    return render(request, 'puzzle2/test.html')


def answer(request):
    if "furnace" == request.POST['text_input'].lower():
        return HttpResponseRedirect(reverse('puzzle2:success'))
    else:
        return HttpResponseRedirect(reverse('puzzle2:fail'))


def success(request):
    return render(request, 'puzzle2/qr.html')

countdown/templates/countdown/counter.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

{% endblock scripts %}

{% block title %}{% endblock title %}

{% block content %}
    <video autoplay muted loop id="myVideo">
    <source src="{% static 'code.mp4' %}" type="video/mp4">
    </video>
    <div class="timer">
    <h1 id="word">Everywhere</h1>
    <div id="clockdiv">
      <div>
        <span class="days" id="day"></span>
        <div class="smalltext" style="color:#000;">Days</div>
      </div>
      <div>
        <span class="hours" id="hour"></span>
        <div class="smalltext" style="color:#000;">Hours</div>
      </div>
      <div>
        <span class="minutes" id="minute"></span>
        <div class="smalltext" style="color:#000;">Minutes</div>
      </div>
      <div>
        <span class="seconds" id="second"></span>
        <div class="smalltext" style="color:#000;">Seconds</div>
      </div>
    </div>
        <h2 id="demo"></h2>
    </div>
    <script>
        function randomness() {
                word = "";
                const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                for (let i = 0; i < 10; i++) {
                    word += alphabet[Math.floor(Math.random() * alphabet.length)];
                }
                return word;
            }
        var deadline = new Date(Date.UTC(2023, 3, 29, 15, 0, 0)).getTime();

        var x = setInterval(function() {

            var now = new Date().getTime();
            var t = deadline - now;
            var days = Math.floor(t / (1000 * 60 * 60 * 24));
            var hours = Math.floor((t % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((t % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((t % (1000 * 60)) / 1000);
            document.getElementById("day").innerHTML = days;
            document.getElementById("hour").innerHTML = hours;
            document.getElementById("minute").innerHTML = minutes;
            document.getElementById("second").innerHTML = seconds;
            var timer = Math.floor((t % (1000 * 60)) / 1000) % 12;
            if (timer < 1) {
                var word = "NOONE";
            } else if (timer < 3) {
                var word = randomness();
            } else if (timer < 4) {
                var word = "EVERYONE";
            } else if (timer < 6) {
                var word = randomness();
            } else if (timer < 7) {
                var word = "NOWHERE";
            } else if (timer < 9) {
                var word = randomness();
            } else if (timer < 10) {
                var word = "EVERYWHERE";
            } else {
                var word = randomness();
                }
            document.getElementById("word").innerHTML = word;
        if (t < 0) {
                clearInterval(x);
                document.getElementById("word").innerHTML = "TIME UP";
                document.getElementById("day").innerHTML ='0';
                document.getElementById("hour").innerHTML ='0';
                document.getElementById("minute").innerHTML ='0' ;
                document.getElementById("second").innerHTML = '0';
                document.getElementById("demo").innerHTML = "Go to the Home";
                };
        }, 100);
    </script>
{% endblock content %}

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'sigil.ico' %}"/>
<!--        <link rel="stylesheet" href="{% static 'bootstrap-5.0.0-beta1-dist/css/bootstrap.css' %}">-->
<!--        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
        <title>01111000{% block title %}{% endblock title %}</title>
        <style>
            {% block style %}
            {% endblock style %}
        </style>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

homepage/templates/homepage/index.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

{% endblock scripts %}

{% block title %}{% endblock title %}

{% block content %}
    <img src="{% static 'sigil2.png' %}" class="sigil" onclick="location.href='{% url 'puzzle2:index' %}'">
{% endblock content %}

puzzle2/templates/puzzle2/fail.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

{% endblock scripts %}

{% block title %}{% endblock title %}

{% block content %}
<img src="{% static 'sigil2.png' %}" class="sigil2" onclick="location.href='{% url 'puzzle2:index' %}'">
<h2>Incorrect</h2>
<img src="{% static 'sigil2.png' %}" class="sigil2" onclick="location.href='{% url 'puzzle2:index' %}'">
{% endblock content %}

puzzle2/templates/puzzle2/index.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

{% endblock scripts %}

{% block title %}{% endblock title %}

{% block content %}
<div class="buttons">
    <div class="grid-wrapper">
      {% for letter in letters %}
        <div class="grid-item">
          {% if forloop.counter == 54 %}
            <button onclick="location.href='{% url 'puzzle2:test' %}'" class="button-89">{{ letter }}</button>
          {% else %}
            <button onclick="location.href='{% url 'puzzle2:fail' %}'" class="button-89">{{ letter }}</button>
          {% endif %}
        </div>
      {% endfor %}
    </div>
</div>
{% endblock content %}

puzzle2/templates/puzzle2/qr.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

{% endblock scripts %}

{% block title %}{% endblock title %}

{% block content %}
    <video autoplay muted loop id="myVideo">
    <source src="{% static 'code.mp4' %}" type="video/mp4">
    </video>
<p>
1fc57f<br>
105541<br>
17565d<br>
17415d<br>
175f5d<br>
105c41<br>
1fd57f<br>
001000<br>
1a6776<br>
0fbea7<br>
17fe79<br>
1615fb<br>
104ee2<br>
0018f5<br>
1fd35e<br>
10486b<br>
174de1<br>
175cf3<br>
174ef5<br>
105330<br>
1fd482
</p>
{% endblock content %}

puzzle2/templates/puzzle2/test.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

{% endblock scripts %}

{% block title %}{% endblock title %}

{% block content %}
    <video autoplay muted loop id="myVideo">
    <source src="{% static 'code.mp4' %}" type="video/mp4">
    </video>

    <p>What was the trail?</p>
    <br />&nbsp;
    <form action="{% url 'puzzle2:answer' %}" method="post">
    {% csrf_token %}
    <input type="text" id="text_input" name="text_input" class="text-input">
    <input type="submit" value="Submit" class="button-28">
    </form>
{% endblock content %}